import type { NextPage } from 'next'
import Head from 'next/head'
import Header from '../components/Header'
import MainLayout from '../components/MainLayout'


const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainLayout
        header={<Header name='Battle Through The Heavens' />}
        content={<p>AAAAAA</p>}
        sidebar={<p>Sidebar</p>}
      />
        
    </>
  )
}

export default Home
