import type { NextPage } from "next";
import Head from "next/head";
import Header from "../components/Header";
import MainLayout from "../components/MainLayout";
import Chapter from "../modules/Chapter";
import SidebarNothing from "../modules/SidebarNothing";
import SidebarSelected from "../modules/SidebarSelected";
import { useChapterContext } from "../providers/ChapterProvider";
import { useSelectedObjectContext } from "../providers/SelectedObjectProvider";

const Home: NextPage = () => {
  const { chapter } = useChapterContext();
  const { stylingObject } = useSelectedObjectContext();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainLayout
        header={<Header name="Battle Through The Heavens" chapter={chapter} />}
        content={<Chapter />}
        sidebar={
          stylingObject ? (
            <SidebarSelected object={stylingObject} />
          ) : (
            <SidebarNothing />
          )
        }
      />
    </>
  );
};

export default Home;
