import type { NextPage } from 'next'
import Head from 'next/head'
import Header from '../components/Header'
import MainLayout from '../components/MainLayout'
import Sidebar from '../components/Sidebar'
import Chapter from '../modules/Chapter'
import { useChapterContext } from '../providers/ChapterProvider'

const Home: NextPage = () => {
  const { chapter } = useChapterContext();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainLayout
        header={<Header name='Battle Through The Heavens' chapter={chapter} />}
        content={<Chapter />}
        sidebar={<Sidebar />}
      />
        
    </>
  )
}

export default Home
